function inputs = inputs_reader(filename)
%IMPORTFILE Import data from a text file
%  INPUTS = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the numeric data.
%
%  INPUTS = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  inputs = importfile("H:\OneDrive\Documents\Work\Machine Learning\4YP\HPCAI.Data\raw_data_2080ti_constant_multiplier\cf-650__bw-130__tsamp-64__chans-512\inputs.dat", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 10-Feb-2021 09:11:29

    dataLines = [2, Inf];
filename = strcat(filename,'/inputs.dat');

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["cf", "Bw", "Tsamp", "Chans"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
inputs = readtable(filename, opts);

%% Convert to output type
inputs = table2array(inputs);
end