%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: H:\OneDrive\Documents\Work\Machine Learning\4YP\HPCAI.Data\raw_data\cf-2000__bw-500__tsamp-32__chans-1024\timenohash.txt
%
% Auto-generated by MATLAB on 26-Oct-2020 15:04:59

function [data] = time_log_importer(path) 
%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 17);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "e05", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16", "VarName17"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Import the data
%fullpath = strcat("H:\OneDrive\Documents\Work\Machine Learning\4YP\HPCAI.Data\raw_data\",path,"\timenohash.txt");
folder = pwd;
fullpath = strcat(folder,"\",path,"\timenohash.txt");
data = readtable(fullpath, opts);

%% Convert to output type
data = table2array(data);

%% Clear temporary variables
clear opts

return;